apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${ORG}-${APP}-${ENV}
  namespace: argocd
  labels:
    astrolift.dev/org: ${ORG}
    astrolift.dev/app: ${APP}
    astrolift.dev/env: ${ENV}
spec:
  project: ${ORG}

  source:
    repoURL: "${REPO_URL}"
    targetRevision: "${REPO_REVISION}"
    path: "apps/${APP}/${ENV}"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${ORG}-${APP}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
