#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Astrolift — build aws/outputs/<env>.env from terraform outputs
#
# Reads `terraform output -json` from aws/environments/<env>/, joins it
# with the live RDS password from Secrets Manager, and emits the env
# file Helm + cold-boot.sh + the astro CLI consume.
#
# Usage:
#   ./aws/scripts/build-env.sh <dev|stg|prd>
#
# Output: aws/outputs/<env>.env (gitignored).
# -----------------------------------------------------------------------------

set -euo pipefail

ENV="${1:?Usage: build-env.sh <dev|stg|prd>}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AWS_DIR="$(dirname "${SCRIPT_DIR}")"
ENV_DIR="${AWS_DIR}/environments/${ENV}"
OUT_DIR="${AWS_DIR}/outputs"
OUT_FILE="${OUT_DIR}/${ENV}.env"

[[ -d "${ENV_DIR}" ]] || { echo "env not found: ${ENV_DIR}" >&2; exit 1; }
mkdir -p "${OUT_DIR}"

echo "Pulling terraform outputs from ${ENV_DIR}..."
TF_OUT=$(terraform -chdir="${ENV_DIR}" output -json)

# Helper: read a string output by name, default to empty.
get() { echo "${TF_OUT}" | jq -r --arg k "$1" '.[$k].value // ""'; }
# Helper: read a list output by name and CSV-join.
get_list() { echo "${TF_OUT}" | jq -r --arg k "$1" '.[$k].value | join(",") // ""'; }

REGION=$(get aws_region)
ACCOUNT=$(get aws_account_id)
EKS_NAME=$(get eks_cluster_name)
EKS_ENDPOINT=$(get eks_cluster_endpoint)
EKS_OIDC=$(get eks_oidc_provider_arn)

DB_ARN=$(get db_credentials_arn)
DB_HOST=$(get rds_endpoint)
DB_NAME=$(get rds_database_name)

# DB credentials live in Secrets Manager, not in tf state. Fetch via AWS CLI.
echo "Fetching DB credentials from Secrets Manager..."
DB_SECRET=$(aws secretsmanager get-secret-value \
  --secret-id "${DB_ARN}" \
  --query SecretString \
  --output text)
DB_USER=$(echo "${DB_SECRET}" | jq -r '.username')
DB_PASS=$(echo "${DB_SECRET}" | jq -r '.password')

REDIS_HOST=$(get redis_endpoint)
REDIS_PORT=$(get redis_port)

S3_BUCKET=$(get s3_artifacts_bucket)
S3_BUCKET_ARN=$(get s3_artifacts_bucket_arn)
ECR=$(get ecr_registry)
SECRETS_PREFIX=$(get secrets_manager_prefix)
IRSA_PATH=$(get irsa_role_path)

cat > "${OUT_FILE}" <<EOF
# Astrolift AWS outputs — ${ENV} (generated by build-env.sh; do not edit by hand)
# Source: terraform -chdir=aws/environments/${ENV} output -json
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Region + identity
AWS_REGION=${REGION}
AWS_ACCOUNT_ID=${ACCOUNT}
ENVIRONMENT=${ENV}

# Cluster
EKS_CLUSTER_NAME=${EKS_NAME}
EKS_CLUSTER_ENDPOINT=${EKS_ENDPOINT}
EKS_OIDC_PROVIDER_ARN=${EKS_OIDC}

# Control-plane datastores
DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}/${DB_NAME}
REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}

# Object storage
S3_ARTIFACTS_BUCKET=${S3_BUCKET}
S3_ARTIFACTS_BUCKET_ARN=${S3_BUCKET_ARN}

# Container registry
ECR_REGISTRY=${ECR}

# Secrets
SECRETS_MANAGER_PREFIX=${SECRETS_PREFIX}
DB_CREDENTIALS_ARN=${DB_ARN}

# IRSA path (drivers create roles under this path)
IRSA_ROLE_PATH=${IRSA_PATH}
EOF

chmod 600 "${OUT_FILE}"  # contains DB password

echo "Wrote ${OUT_FILE}"
echo "Use with helm:"
echo "  helm upgrade --install astrolift ./helm/astrolift \\"
echo "    -f ./helm/astrolift/values.aws.yaml \\"
echo "    \$(cat ${OUT_FILE} | grep -E '^(EKS|DATABASE|REDIS|S3|ECR|SECRETS)' | sed 's/^/--set api.env./;s/=/=/' | tr '\\n' ' ')"
